server:
  port: 8094

spring:
  output:
    ansi:
      enabled: always
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true


  #### database ??
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: springryan
    password: ryan

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

    database: oracle
    properties:
      hibernate:
        format_sql: true
        show-sql: true
        dialect: org.hibernate.dialect.Oracle12cDialect

#### log ??  fatal > error > warn > info > debug
logging:
  level:
   org.hibernate.SQL: debug
   org.hibernate.type: trace #파라미터를 보여준다.

file:
  path: C:/upload/

pagination:
  size: 5


