server:
  port: 8091

spring:
  output:
    ansi:
      enabled: always
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

  thymeleaf:
    cache: false

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  #    mvc:
#      view:
#        prefix: /WEB-INF/views
#        suffix: .jsp

  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: springryan
    password: ryan

mybatis:
  config-location: classpath:mapper/config/config.xml
  mapper-locations: classpath:mapper/sql/**/*.xml
  #type-aliases-package: com.ryan9025.gallery.dto


file:
  path: C:/upload/




